github: [m_irfan_arshad]  # your GitHub username (max 4)
patreon: irfandigitify   # optional
open_collective:       # leave empty if not using
ko_fi: irfanarshad
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: irfanarshad
thanks_dev:
custom: ['https://digitify.com', 'https://yap.com']
